name: Java CI/CD Pipeline with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '25' ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
          cache: maven

      - name: Grant execute permission for Maven wrapper
        run: chmod +x mvnw

      - name: Build and test with Maven Wrapper
        run: ./mvnw clean verify

      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:5.3.0.6276:sonar -Dsonar.projectKey=spring-petclinic -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Archive production jar
        uses: actions/upload-artifact@v4
        with:
          name: spring-petclinic-jar
          path: target/spring-petclinic-*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: [ build ]

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Download Jar from CI
        uses: actions/download-artifact@v4
        with:
          name: spring-petclinic-jar
        path: target

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.EC2_PRIVATE_KEY }}

    - name: Remove any existing app
      run: ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} "fuser -k 8080/tcp || true"

    - name: Copy JAR to EC2
      run: scp -o StrictHostKeyChecking=no target/spring-petclinic-*.jar ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/

    - name: Run the app
      run: ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} "nohup java -jar /home/ubuntu/spring-petclinic-*.jar > app.log 2>&1 &"

